### ISSUE TITLE
Invalid JSON response with PHP 8.1

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingaweb2-module-nagvis#52] opened 2023-05-04 12:17 UTC
With PHP 8.1.18 I get the following error when I want to add a Host/Service to a map:

![nagvis](https://user-images.githubusercontent.com/3973350/236200250-a71d76ce-1105-4987-b0bb-ef3846bedfe6.png)

I also tested with PHP 8.0.28, that works on the same system. I'm not sure if this is related to the NagVis Module or NagVis itself (1.9.34).

# Environment
PHP: 8.1.18
OS: Ubuntu 22.04.2 LTS (Jammy)
Icinga Web 2.11.4
NagVis 1.9.34
NagVis Module: Current master with Icinga DB 140347ab4fae1c5b828b6020656fc18dd9bbbb6d

**Comment by mwaldmueller** [comment] 2023-05-04 12:22
Issue for NagVis: https://github.com/NagVis/nagvis/issues/335

**Comment by lippserd** [comment] 2023-05-04 12:26
Icinga DB uses timestamps with millisecond precision. But I think we could just cast that to `int` wherever we use `last_state_change`.

**Comment by yhabteab** [comment] 2023-10-12 08:02
> Icinga DB uses timestamps with millisecond precision.

This issue isn't caused by our module. Though, the upstream issue is fixed anyway, so I'm going to close this.

**Closed by yhabteab** 2023-10-12 08:02 UTC
